import {useEffect,useState} from 'react';
import type {ReactNode} from 'react';
import type {MapClient} from './client';
import {Badge,DateText} from './widgets';
import {GraphCanvas} from './GraphCanvas';
import {NodePanel} from './NodePanel';
import type {Failure,Incident,MapGraph,MapNode,MapSystem,NodeDetail} from './types';
import './data-map.css';

type Tour={steps:{title:string;layer:string;text:string}[];message:string};
type Search={matches:{id:string;name:string;columns:string[]}[];truncated:boolean};
const names=(id:string)=>id.split('.').slice(-1)[0].replaceAll('_',' ');

export type MapExtension={
 busy?:boolean;lockedSystem?:boolean;allowExplanations?:boolean;showDiagnostics?:boolean;
 controls?:(systemId:string,busy:boolean)=>ReactNode;
 badges?:ReactNode;notice?:ReactNode;incidentNotice?:ReactNode;
 sidebar?:(systemId:string,nodes:MapNode[])=>ReactNode;
 onAction?:()=>Promise<void>;onSystemChange?:(systemId:string)=>void;
};
export function DataMap({client,standalone=false,initialSystemId='commerce-demo',refreshKey=0,extension={},homeLabel='← Data Observability'}:{client:MapClient;standalone?:boolean;initialSystemId?:string;refreshKey?:number;extension?:MapExtension;homeLabel?:string}){
 const {request,initialize}=client;
 const [systems,setSystems]=useState<MapSystem[]>([]),[systemId,setSystemId]=useState(initialSystemId),[graph,setGraph]=useState<MapGraph|null>(null),[allNodes,setAllNodes]=useState<MapNode[]>([]);
 const [node,setNode]=useState<NodeDetail|null>(null),[incidents,setIncidents]=useState<Incident[]>([]),[failure,setFailure]=useState<Failure|null>(null),[tour,setTour]=useState<Tour|null>(null);
 const [advanced,setAdvanced]=useState(false),[error,setError]=useState(''),[localBusy,setBusy]=useState(false),[ready,setReady]=useState(false),[search,setSearch]=useState(''),[matches,setMatches]=useState<Search|null>(null);
 const [files,setFiles]=useState<Record<string,File>>({}),[importId,setImportId]=useState('my-data-system'),[importName,setImportName]=useState('My data system');
 const base=(id=systemId)=>'/map/systems/'+encodeURIComponent(id);
 const busy=localBusy||Boolean(extension.busy),locked=Boolean(extension.lockedSystem);
 const syncActions=async()=>{await extension.onAction?.();};

 async function load(id=systemId,level='overview',focus?:string,layer?:string){
  const query=new URLSearchParams({level});if(focus)query.set('focus',focus);if(layer)query.set('layer',layer);
  const [value,nodes,known]=await Promise.all([request<MapGraph>(base(id)+'/graph?'+query),request<MapGraph>(base(id)+'/graph?level=models'),request<Incident[]>(base(id)+'/incidents')]);
  setGraph(value);setAllNodes(nodes.nodes);setIncidents(known);await syncActions();
 }
 useEffect(()=>{let alive=true;(async()=>{try{await initialize();const available=await request<MapSystem[]>('/map/systems');if(!alive)return;setSystems(available);const id=available.some(s=>s.id===initialSystemId)?initialSystemId:(available[0]?.id||initialSystemId);setSystemId(id);extension.onSystemChange?.(id);await load(id);if(alive)setReady(true);}catch(e){if(alive){setError((e as Error).message);setReady(true);}}})();return()=>{alive=false;};},[]);
 useEffect(()=>{if(!ready)return;setFailure(null);setTour(null);setNode(null);setMatches(null);void work(async()=>{await load();});},[refreshKey]);
 async function work(action:()=>Promise<void>){if(busy)return;setBusy(true);setError('');try{await action();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const selectNode=(id:string)=>void work(async()=>{setTour(null);setFailure(null);const value=await request<NodeDetail>(base()+'/nodes/'+encodeURIComponent(id));setNode(value);await syncActions();await load(systemId,'models',id);});
 const stage=(layer:string)=>void work(async()=>{setNode(null);setFailure(null);setTour(null);await load(systemId,'models',undefined,layer);});
 const overview=()=>void work(async()=>{setFailure(null);setNode(null);setTour(null);await load();});
 const showFailure=(id:string)=>void work(async()=>{setTour(null);setNode(null);setFailure(await request<Failure>(base()+'/incidents/'+encodeURIComponent(id)));await syncActions();});
 async function importArtifacts(){if(!files.manifest)throw new Error('Choose a manifest.json file.');const payload:Record<string,unknown>={system_id:importId,name:importName};let total=0;for(const [kind,file] of Object.entries(files)){total+=file.size;if(total>7*1024*1024)throw new Error('The selected artifacts exceed this local upload limit.');try{payload[kind]=JSON.parse(await file.text());}catch{throw new Error('An artifact is not valid JSON. The saved graph was not changed.');}}
  const saved=await request<{system_id:string}>('/map/systems/import','POST',payload);setSystems(await request('/map/systems'));setSystemId(saved.system_id);setNode(null);setFailure(null);setTour(null);extension.onSystemChange?.(saved.system_id);await load(saved.system_id);
 }
 const graphNodes=failure?failure.failure_path.nodes.slice(0,14):graph?.nodes||[];
 const pathIds=new Set(graphNodes.map(n=>n.id));const graphEdges=failure?failure.failure_path.edges.filter(e=>pathIds.has(e.from_node)&&pathIds.has(e.to_node)):graph?.edges||[];
 return <div className={standalone?'dm-standalone':'dm-workspace'}>{standalone&&<header className="dm-standalone-header"><a href="/">{homeLabel}</a><span>Data System Map</span><button onClick={()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='light'?'dark':'light';}}>Change appearance</button></header>}
 <div className="page-heading"><div><div className="eyebrow">UNDERSTAND THE SYSTEM. FOLLOW THE EVIDENCE.</div><h1>Data System Map</h1><p>See where data starts, what changes it, and which business outputs depend on it.</p></div><label className="dm-advanced"><input type="checkbox" checked={advanced} onChange={e=>setAdvanced(e.target.checked)}/>Advanced details</label></div>
 {error&&<div className="notice error" role="alert"><span>{error}</span><button onClick={()=>setError('')} aria-label="Dismiss map error">×</button></div>}
 {!ready?<section className="panel loading">Loading metadata…</section>:!graph?<section className="panel"><h2>Map unavailable</h2><p>Check the local application and its metadata profile.</p></section>:<>
 <div className="dm-controls"><label>System<select value={systemId} disabled={busy||locked} onChange={e=>void work(async()=>{const id=e.target.value;setSystemId(id);setNode(null);setFailure(null);setTour(null);extension.onSystemChange?.(id);await load(id);})}>{systems.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><div className="tag-row"><Badge tone="green">{graph.sample?'Synthetic demonstration':'Imported metadata'}</Badge><Badge>Local · metadata only</Badge>{extension.badges}</div>{extension.controls?.(systemId,busy)}</div>
 {extension.notice}
 <div className="dm-search-row"><form onSubmit={e=>{e.preventDefault();void work(async()=>{setMatches(await request<Search>(base()+'/search?q='+encodeURIComponent(search)));await syncActions();});}}><input aria-label="Search system metadata" placeholder="Find a model, column or business term" value={search} onChange={e=>setSearch(e.target.value)}/><button disabled={busy||!search.trim()}>Search</button></form><button disabled={busy||extension.allowExplanations===false} onClick={()=>void work(async()=>{setTour(await request<Tour>(base()+'/explain'));await syncActions();setFailure(null);})}>Explain this system</button><button disabled={busy} onClick={overview}>System overview</button></div>
 {matches&&<div className="panel dm-search-results"><h3>Metadata matches</h3>{matches.matches.length?matches.matches.map(n=><button key={n.id} onClick={()=>selectNode(n.id)}>{n.name}{n.columns.length?' · '+n.columns.join(', '):''} ↗</button>):<p>No match. Relationships are not guessed from a search.</p>}{matches.truncated&&<p className="fine">First 100 matches. Refine your search.</p>}</div>}
 {tour&&<section className="panel dm-tour"><h2>A guided system tour</h2><p>{tour.message}</p><ol>{tour.steps.map(s=><li key={s.layer}><button className="text-button" onClick={()=>stage(s.layer)}>{s.title} ↗</button><p>{s.text}</p></li>)}</ol></section>}
 <section className="panel dm-graph-panel"><div className="section-heading"><div><div className="eyebrow">{failure?'INCIDENT PATH':graph.level==='overview'?'START WITH THE BIG PICTURE':'ONE PART OF THE SYSTEM'}</div><h2>{failure?'Follow the observed failure':graph.name}</h2></div><span className="fine">{failure?'Requested failure path':graph.level==='overview'?'Select a stage to expand':'Select a node for evidence'}</span></div>
 <GraphCanvas nodes={graphNodes} edges={graphEdges} stages={!failure&&graph.level==='overview'?graph.stages:undefined} stageEdges={graph.stage_edges} selected={node?.id} onNode={selectNode} onStage={stage}/><div className="dm-legend">{['HEALTHY','WARNING','FAILED','UNKNOWN'].map(s=><span key={s}><i className={'dm-status-dot '+s.toLowerCase()}/>{s.toLowerCase()}</span>)}<span>Arrows: declared dependencies</span></div>{(graph.truncated||failure?.failure_path.truncated||(failure&&failure.failure_path.nodes.length>14))&&<p className="fine">This focused view is limited to 14 resources. Search or select a node to inspect another part.</p>}</section>
 {graph.issues.length>0&&<details className="dm-issues panel"><summary>Metadata limits and conflicts · {graph.issues.length}</summary>{graph.issues.map((i,index)=><p key={index}><Badge>{i.provenance.classification}</Badge> {i.message}</p>)}</details>}
 <div className="dm-main-grid"><div className="dm-main-column">{node&&<NodePanel client={client} key={node.id} node={node} systemId={systemId} advanced={advanced} onSelect={selectNode} onAction={syncActions} onError={setError}/>}
 {!node&&<section className="panel dm-orientation"><h2>{failure?'Observed failure and impact':'Two useful starting points'}</h2>{failure?<><div className="tag-row"><Badge>FACT</Badge><strong>{names(failure.observed_failure)}</strong></div><p>{failure.why}</p>{failure.evidence.map(t=><div className="dm-test" key={t.test_id}><strong>{t.test_name}</strong><p>{t.evidence||'A recorded test reports failure.'}</p><p className="fine">{t.provenance.source}</p></div>)}{failure.execution_evidence.map((e,i)=><div className="dm-test" key={'execution-'+i}><Badge>FACT · recorded execution</Badge><strong>{e.operation||'Unknown operation'} · {e.reported_status}</strong><p>{e.error||'Recorded execution failed.'}</p><p className="fine">{e.provenance.source}</p></div>)}<h3>Affected business outputs</h3><div className="dm-node-links">{failure.impact.affected_outputs.map(n=><button key={n.id} onClick={()=>selectNode(n.id)}>{n.name} ↗</button>)}</div>{extension.showDiagnostics!==false&&failure.inference&&<div className="dm-learning-evidence"><Badge tone="amber">INFERENCE · evidence-supported suspicion</Badge><h3>{failure.first_suspicious_node?'Earliest observed anomaly: '+names(failure.first_suspicious_node):'Origin remains uncertain'}</h3><p>{failure.inference.message}</p>{failure.last_known_good?.length!==0&&<p>Last comparable good check: {failure.last_known_good?.map(names).join(', ')}</p>}<p className="dm-unknown">First bad node cannot yet be established.</p><h3>Next verification step</h3><p>{failure.next_step}</p><ul>{failure.uncertainty?.slice(1).map(s=><li key={s}>{s}</li>)}</ul></div>}{extension.incidentNotice}</>:<><div className="dm-starting-points"><div><strong>“I just joined. How does this work?”</strong><p>Expand a stage, open a resource, then follow its direct inputs and business outputs.</p></div><div><strong>“Something broke. Where do I start?”</strong><p>Start with a recorded failure, inspect upstream evidence, and distinguish facts from suspicions.</p></div></div><p className="fine">Grain means what one row represents. A dependency is a declared relationship. Healthy means a recorded check succeeded, not that every possible check passed.</p></>}</section>}
 <section className="panel dm-import"><details><summary>Import dbt artifact files</summary><p>Choose local JSON exports. No warehouse connection, SQL or project code will be executed.</p><div className="dm-form-grid"><label className="dm-field">System ID<input value={importId} onChange={e=>setImportId(e.target.value)} disabled={locked}/></label><label className="dm-field">System name<input value={importName} onChange={e=>setImportName(e.target.value)} disabled={locked}/></label></div>{[['manifest','manifest.json (required)'],['run_results','run_results.json'],['catalog','catalog.json'],['freshness','sources.json or freshness.json']].map(([kind,label])=><label key={kind} className="dm-field">{label}<input type="file" accept=".json,application/json" disabled={locked} onChange={e=>{const file=e.target.files?.[0];setFiles(f=>{const next={...f};if(file)next[kind]=file;else delete next[kind];return next;});}}/></label>)}<button disabled={busy||locked||!files.manifest} onClick={()=>void work(importArtifacts)}>Import metadata</button><p className="fine">Failed imports preserve the saved graph. Supported dbt artifact subsets and security limits are documented in this project.</p></details></section></div>
 <aside className="dm-evidence-column"><section className="panel dm-incident-list"><div className="eyebrow">OBSERVED FAILURES</div><h2>Start from what failed</h2>{incidents.length?incidents.map(i=><div key={i.id} className="dm-incident"><div className="tag-row"><Badge tone="amber">FAILED</Badge><strong>{i.name}</strong></div><p>{i.summary}</p><button disabled={busy} onClick={()=>showFailure(i.id)}>Show failure path</button></div>):<p>No failures are recorded in the supplied artifacts. This does not establish complete system health.</p>}</section>
 {extension.sidebar?.(systemId,allNodes)}</aside></div>
 <div className="dm-footer">Facts follow artifact provenance. Suspicions stay labeled. AI is unavailable in this slice; deterministic exploration works offline.</div>
 </>}
 </div>;
}
