import {useState} from 'react';
import type {MapClient} from './client';
import {Badge,DateText} from './widgets';
import type {Impact,NodeDetail,Relation,SqlView} from './types';

export function NodePanel({client,node,systemId,advanced,onSelect,onAction,onError}:{client:MapClient;node:NodeDetail;systemId:string;advanced:boolean;onSelect:(key:string)=>void;onAction:()=>Promise<void>;onError:(message:string)=>void}){
 const request=client.request;
 const [tab,setTab]=useState('about');const [sql,setSql]=useState<SqlView|null>(null);const [relation,setRelation]=useState<Relation|null>(null);const [impact,setImpact]=useState<Impact|null>(null);const [lineage,setLineage]=useState('');const [busy,setBusy]=useState(false);
 const base='/map/systems/'+encodeURIComponent(systemId)+'/nodes/'+encodeURIComponent(node.id);
 async function open(next:string){setBusy(true);setTab(next);try{
  if(next==='sql')setSql(await request<SqlView>(base+'/sql'));
  else if(next==='upstream'||next==='downstream')setRelation(await request<Relation>(base+'/'+next));
  else if(next==='impact')setImpact(await request<Impact>(base+'/impact'));
  else if(next==='schema'||next==='tests')await request(base+'/'+next);
  await onAction();
 }catch(e){onError((e as Error).message);}finally{setBusy(false);}}
 const links=(items:{id:string;name:string}[])=>items.length?<div className="dm-node-links">{items.map(n=><button key={n.id} onClick={()=>onSelect(n.id)}>{n.name} ↗</button>)}</div>:<p className="fine">None declared in this snapshot.</p>;
 return <section className="panel dm-detail" aria-label="Node details"><div className="dm-detail-heading"><div><div className="eyebrow">SELECTED RESOURCE</div><h2>{node.name}</h2></div><Badge tone={node.status==='FAILED'?'amber':'neutral'}>{node.status}</Badge></div><p>{node.description||'Description unknown.'}</p>
 <div className="dm-detail-tabs" role="tablist" aria-label="Node detail views">{[['about','About'],['schema','Schema'],['tests','Recorded tests'],['upstream','Upstream'],['downstream','Downstream'],['impact','Impact'],['sql','SQL'],['evidence','Evidence']].map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} onClick={()=>void open(id)} disabled={busy||(id==='sql'&&!node.sql_available)}>{label}</button>)}</div>
 {tab==='about'&&<><dl className="dm-properties"><div><dt>What is this?</dt><dd>{node.node_type}</dd></div><div><dt>Declared grain</dt><dd>{node.grain||'Grain unknown'}</dd></div><div><dt>Declared primary key</dt><dd>{node.primary_keys?.join(', ')||'Primary key unknown'}</dd></div><div><dt>Owner</dt><dd>{node.owner||'Owner unknown'}</dd></div><div><dt>Source system</dt><dd>{node.source_system||'Source system unknown'}</dd></div></dl><h3>Direct inputs</h3>{links(node.inputs)}<h3>Direct outputs</h3>{links(node.outputs)}<p className="fine">A successful execution does not prove that grain, tests or business numbers are correct.</p>{node.executions.map((e,i)=><div className="dm-evidence-row" key={i}><Badge>FACT</Badge><span>{e.operation||'Unknown operation'} · {e.reported_status}</span><DateText value={e.completed_at}/></div>)}</>}
 {tab==='schema'&&<><p className="fine">Declared and catalog-reported fields. Unknown nullability stays unknown.</p>{node.columns.length?<div className="table-scroll"><table><thead><tr><th>Column</th><th>Type</th><th>Nullable</th><th>Checks</th><th>Flow</th></tr></thead><tbody>{node.columns.map(c=><tr key={c.name}><td><code>{c.name}</code></td><td>{c.data_type||'Unknown'}</td><td>{c.nullable===null?'Unknown':c.nullable?'Yes':'No'}</td><td>{c.tests.length||'—'}</td><td><button className="text-button" onClick={()=>void (async()=>{try{const value=await request<{message:string}>(base+'/columns/'+encodeURIComponent(c.name)+'/lineage');setLineage(value.message);await onAction();}catch(e){onError((e as Error).message);}})()}>Column flow</button></td></tr>)}</tbody></table></div>:<p>Schema unknown. Import catalog metadata if available.</p>}{lineage&&<div className="notice" role="status">{lineage}</div>}</>}
 {tab==='tests'&&<><p className="fine">Recorded results from artifacts. This action does not execute dbt.</p>{node.tests.length?node.tests.map(t=><div key={t.test_id} className="dm-test"><div className="tag-row"><Badge>FACT</Badge><Badge tone={t.status==='FAILED'?'amber':'neutral'}>{t.status}</Badge><strong>{t.test_name}</strong></div><p>{t.evidence||'No recorded result message.'}</p><p className="fine">Failure count: {t.failures??'Unknown'} · Association: {t.association} · {t.provenance.source}</p></div>):<p>No associated test definitions or results were supplied.</p>}</>}
 {(tab==='upstream'||tab==='downstream')&&relation&&<><h3>Direct {tab==='upstream'?'parents':'children'}</h3>{links(relation.direct)}<h3>Transitive dependencies</h3>{links(relation.transitive)}<p className="fine">These relationships are declared by the artifact, rather than inferred from model names.</p></>}
 {tab==='impact'&&impact&&<><h3>Direct dependencies</h3>{links(impact.direct)}<h3>Transitive dependencies</h3>{links(impact.transitive)}<h3>Affected business outputs</h3>{links(impact.affected_outputs)}<p className="fine">Dependency impact identifies consumers to check. It does not prove every consumer contains wrong values.</p></>}
 {tab==='sql'&&sql&&<><p className="fine">SQL from imported metadata; displayed as text and never executed.</p><h3>Model SQL</h3><pre className="dm-code">{sql.sql||'SQL unavailable.'}</pre>{advanced&&<><h3>Compiled SQL</h3><pre className="dm-code">{sql.compiled_sql||'Compiled SQL unavailable.'}</pre></>}</>}
 {tab==='evidence'&&<><h3>Recorded measurements</h3>{node.observations.length?node.observations.map((o,i)=><div className="dm-observation" key={i}><Badge>FACT · reported measurement</Badge><strong>{o.evidence_type.replaceAll('_',' ')}</strong><dl className="dm-properties"><div><dt>Expected</dt><dd>{o.expected??'Unknown'}</dd></div><div><dt>Observed</dt><dd>{o.actual??'Unknown'}</dd></div><div><dt>Comparison</dt><dd>{o.comparison_key||'Unknown'}</dd></div></dl><p className="fine">{o.provenance.source} · {o.provenance.timestamp||'Time unknown'}</p></div>):<p>No measurements were supplied for this node. That absence is not proof of health.</p>}<h3>Recent changes</h3><p>{node.recent_changes.message}</p>{advanced&&<><h3>Provenance</h3><pre className="dm-code">{JSON.stringify(node.provenance,null,2)}</pre><div className="fine">Resource identity: {node.id}</div></>}</>}
 </section>;
}
