import type {Dashboard as DashboardData} from './types';
import {Badge,DateText,Empty,Selection} from './components';

export function Dashboard({data,onContinue,onNavigate,onAttempt}:{data:DashboardData;onContinue:()=>void;onNavigate:(p:string)=>void;onAttempt:(id:string)=>void}) {
 const stats=data.stats;
 const categories=['SQL','Modeling','Metrics','dbt','Data Quality','Debugging'];
 return <>
  <div className="page-heading"><div><div className="eyebrow">YOUR TRAINING WORKSPACE</div><h1>Make your next session count.</h1></div><Badge tone="green">● Local-first</Badge></div>
  <div className="hero-grid"><section className="hero panel"><div className="eyebrow">DELIBERATE PRACTICE, REAL EVIDENCE</div><h2>Build judgment.<br/><span>Prove it in SQL.</span></h2><p>Work through realistic data problems. Execute your solution, test the edge cases, and let your evidence guide what comes next.</p><button className="primary large" onClick={onContinue}>{data.active_attempt?'Resume Training':'Continue Training'} <span>↗</span></button><div className="hero-foot">{data.active_attempt?<>Saved {data.active_attempt.status} · {data.active_attempt.exercise.title}</>:<>12 original SQL challenges · no API key required</>}</div></section><section className="panel next-card"><Selection value={data.recommendation}/></section></div>
  <div className="stats-grid">{[[stats.solved,'Exercises solved','Distinct problems'],[stats.attempts,'Completed attempts','All submitted work'],[`${stats.tested}/${stats.total_competencies}`,'Competencies tested','Scoped evidence'],[stats.due_reviews,'Reviews due','Transfer before repetition']].map(([value,label,note])=><div className="stat panel" key={label}><div className="stat-value">{value}</div><div className="stat-label">{label}</div><div className="fine">{note}</div></div>)}</div>
  <div className="section-heading"><h2>Choose your focus</h2><span className="muted">One meaningful problem at a time</span></div>
  <div className="mode-grid"><button className="mode-card panel" onClick={()=>onNavigate('practice')}><div className="mode-icon">⌘</div><h3>Practice</h3><p>Choose a competency and difficulty. Use progressive hints when you need them.</p><span>Find a challenge →</span></button><button className="mode-card panel" onClick={()=>onNavigate('interview')}><div className="mode-icon">◎</div><h3>SQL Interview</h3><p>A stricter SQL round with clarifications, optional timing, and audited assistance.</p><span>Start a round →</span></button><button className="mode-card panel" onClick={()=>onNavigate('mistakes')}><div className="mode-icon">↺</div><h3>Weakness Review</h3><p>{stats.open_mistakes?`${stats.open_mistakes} unresolved test patterns. Retest the concept in a different context.`:'Recorded mistakes will shape your next exercises. Untested does not mean weak.'}</p><span>Review evidence →</span></button></div>
  <div className="bottom-grid"><section className="panel"><div className="section-heading"><h2>Competency coverage</h2><button className="text-button" onClick={()=>onNavigate('competencies')}>Explore map →</button></div><div className="coverage-list">{categories.map(category=>{const rows=data.competencies.filter(c=>c.category===category);const tested=rows.filter(c=>c.attempts>0).length;return <div key={category}><div className="coverage-label"><span>{category}</span><span>{tested}/{rows.length} tested</span></div><div className="progress-track"><div style={{width:`${tested/Math.max(1,rows.length)*100}%`}}/></div></div>;})}</div><p className="fine">Coverage is not mastery. Stronger levels require independent transfer and later retests.</p></section><section className="panel"><div className="section-heading"><h2>Recent attempts</h2><button className="text-button" onClick={()=>onNavigate('history')}>All history →</button></div>{data.history.length?<div className="recent-list">{data.history.slice(0,4).map(h=><button key={h.id} onClick={()=>onAttempt(h.id)}><div><strong>{h.title}</strong><span><DateText value={h.at}/> · L{h.difficulty}</span></div><Badge tone={h.result.outcome==='Correct'?'green':'amber'}>{h.result.outcome}</Badge></button>)}</div>:<Empty title="Your first evidence starts here" body="Complete an exercise to see the outcome, assistance used, and the competencies it tested."/>}</section></div>
 </>;
}
