import {useState} from 'react';
import type {Competency,Dashboard,Exercise} from './types';
import {Badge,DateText,Empty} from './components';

export function Library({exercises,data,onStart,mode='practice'}:{exercises:Exercise[];data:Dashboard;onStart:(payload:unknown)=>void;mode?:string}) {
 const [competency,setCompetency]=useState('');const [difficulty,setDifficulty]=useState('');const [domain,setDomain]=useState('');const [search,setSearch]=useState('');const [timed,setTimed]=useState(false);
 const rows=exercises.filter(e=>(!competency||e.competencies.includes(competency))&&(!difficulty||e.difficulty===Number(difficulty))&&(!domain||e.domain===domain)&&e.title.toLowerCase().includes(search.toLowerCase()));
 return <><div className="page-heading"><div><div className="eyebrow">EXECUTABLE SQL · CURATED, ORIGINAL PROBLEMS</div><h1>{mode==='interview'?'SQL interview practice':'Exercise library'}</h1><p className="muted">{mode==='interview'?'Hints are disabled. Clarifications and visible test runs are allowed. Full mixed interviews follow in Phase 5.':'Find a deliberate challenge. Results are executed against visible and hidden fixtures.'}</p></div><Badge>{rows.length} challenges</Badge></div><section className="panel filters"><label>Search<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find an exercise…"/></label><label>Competency<select value={competency} onChange={e=>setCompetency(e.target.value)}><option value="">All covered competencies</option>{data.competencies.filter(c=>exercises.some(e=>e.competencies.includes(c.id))).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Difficulty<select value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option value="">All levels</option>{[2,3,4].map(n=><option key={n} value={n}>Level {n}</option>)}</select></label><label>Business domain<select value={domain} onChange={e=>setDomain(e.target.value)}><option value="">All domains</option>{Array.from(new Set(exercises.map(e=>e.domain))).sort().map(d=><option key={d}>{d}</option>)}</select></label></section>{mode==='interview'&&<label className="check-label"><input type="checkbox" checked={timed} onChange={e=>setTimed(e.target.checked)}/>Show elapsed time (informational, no time-based failure)</label>}<div className="library-grid">{rows.map(e=>{const successes=data.history.filter(h=>h.exercise_id===e.id&&h.result.outcome==='Correct');return <article className="exercise-card panel" key={e.id}><div className="tag-row"><Badge tone="green">{e.domain}</Badge><Badge>L{e.difficulty}</Badge><span className="fine">~{e.estimated_duration} min</span></div><h2>{e.title}</h2><p>{e.context}</p><div className="card-skills">{e.competencies.slice(0,3).map(id=><span key={id}>{data.competencies.find(c=>c.id===id)?.name}</span>)}</div><div className="card-footer"><span className="fine">{successes.length?'Previously solved · practice only':'Not yet solved'}</span><button onClick={()=>onStart({mode,exercise_id:e.id,timed})}>Open challenge ↗</button></div></article>;})}</div>{!rows.length&&<Empty title="No challenges match" body="Try a different domain, competency, or difficulty."/>}</>;
}

function CompetencyDetail({competency,onAttempt}:{competency:Competency;onAttempt:(id:string)=>void}) {
 return <div className="competency-detail"><p>{competency.description}</p><div className="explanation-grid"><div><strong>{competency.independent_successes.length}</strong><span>Independent successes</span></div><div><strong>{new Set(competency.independent_successes.map(e=>e.family)).size}</strong><span>Different contexts</span></div><div><strong>{competency.highest_difficulty||'—'}</strong><span>Highest independent level</span></div><div><strong>{competency.unresolved_mistakes}</strong><span>Unresolved test patterns</span></div></div><p className="fine">{competency.level===0?'No submitted evidence. This is unknown, not a weakness.':competency.level===1?'Submitted tests exposed gaps; no successful evidence is recorded.':competency.level===2?'Developing requires more independent successes in different contexts, or resolution of reopened gaps.':'This level reflects the recorded independent successes, transfer and retest requirements.'} Confidence: {competency.confidence}. Explanation quality is unassessed.</p>{competency.recent_attempts.length>0&&<div className="evidence-list">{[...competency.recent_attempts].reverse().map(a=><button key={a.attempt_id} onClick={()=>onAttempt(a.attempt_id)}><span>{a.exercise_id.replace('sql-','').replaceAll('-',' ')} <span className="muted">· L{a.difficulty}</span></span><Badge tone={a.passed?'green':'amber'}>{a.passed?(a.independent?'Independent':'Practice success'):'Test gap'}</Badge><DateText value={a.at}/></button>)}</div>}</div>;
}

export function Competencies({data,onAttempt}:{data:Dashboard;onAttempt:(id:string)=>void}){
 return <><div className="page-heading"><div><div className="eyebrow">MASTERY IS AN EVIDENCE CLAIM</div><h1>Your competency map</h1><p className="muted">Open any competency to inspect the attempts behind its current level.</p></div></div><div className="scale panel">{['Unassessed','Foundational Gap','Developing','Independent','Senior Ready','Strong Senior / Staff Signal'].map((x,i)=><div key={x}><span>{i}</span>{x}</div>)}</div>{Array.from(new Set(data.competencies.map(c=>c.category))).map(category=><section className="competency-group" key={category}><h2>{category}</h2>{data.competencies.filter(c=>c.category===category).map(c=><details className="panel competency-row" key={c.id}><summary><div><strong>{c.name}</strong><span className="fine">{c.attempts} attempts · last tested <DateText value={c.last_tested}/></span></div><Badge tone={c.level>=3?'green':c.level===1?'amber':'neutral'}>{c.label}</Badge><span className="muted">＋</span></summary><CompetencyDetail competency={c} onAttempt={onAttempt}/></details>)}</section>)}</>;
}

export function Mistakes({data,onStart,onAttempt}:{data:Dashboard;onStart:()=>void;onAttempt:(id:string)=>void}){return <><div className="page-heading"><div><div className="eyebrow">PATTERNS, NOT GUESSED WEAKNESSES</div><h1>Mistake review</h1><p className="muted">Failures are recorded by tested contract. Independent transfer is required to close a gap.</p></div><button className="primary" onClick={onStart}>Train the next gap ↗</button></div>{data.mistakes.length?<div className="mistake-grid">{data.mistakes.map(m=><article className="panel mistake-card" key={m.id}><div className="tag-row"><Badge tone={m.status==='OPEN'?'amber':'green'}>{m.status.replaceAll('_',' ')}</Badge><Badge>{m.recurrence_count} occurrence{m.recurrence_count===1?'':'s'}</Badge></div><h2>{data.competencies.find(c=>c.id===m.competency_id)?.name}</h2><h3>{m.label}</h3><p>{m.diagnostic}</p><div className="fine">Last observed <DateText value={m.last_occurrence}/></div><button className="text-button" onClick={()=>onAttempt(m.source_attempts.at(-1)!)}>Inspect source attempt →</button>{m.resolved_evidence.map(e=><p className="fine" key={e.attempt_id}>{e.basis} <button className="text-button" onClick={()=>onAttempt(e.attempt_id)}>View retest</button></p>)}</article>)}</div>:<section className="panel"><Empty title="No observed mistakes yet" body="Untested areas are unknown. The trainer will record patterns when actual submissions fail a tested contract."/></section>}</>;}

export function Reviews({data,onStart}:{data:Dashboard;onStart:(payload:unknown)=>void}){return <><div className="page-heading"><div><div className="eyebrow">LATER EVIDENCE, DIFFERENT CONTEXT</div><h1>Review queue</h1><p className="muted">Due dates prioritize your next session. No background reminders are scheduled.</p></div></div>{data.reviews.length?data.reviews.map(c=><article className="panel review-card" key={c.id}><div><h2>{c.name}</h2><span className="muted">{c.label} · due <DateText value={c.next_review}/></span></div><button className="primary" onClick={()=>onStart({mode:'adaptive',competency:c.id})}>Retest competency ↗</button></article>):<section className="panel"><Empty title="Nothing is due yet" body="After a submission, the review schedule reflects failure, assisted practice, independent success, or cold transfer."/></section>}</>;}

export function History({data,onAttempt}:{data:Dashboard;onAttempt:(id:string)=>void}){return <><div className="page-heading"><div><div className="eyebrow">DURABLE ATTEMPTS · FROZEN EXERCISE VERSIONS</div><h1>Session history</h1></div><Badge>{data.history.length} attempts</Badge></div>{data.active_attempt&&<article className="panel review-card"><div><h3>{data.active_attempt.exercise.title}</h3><p className="muted">Saved {data.active_attempt.status} draft · not evaluated</p></div><button onClick={()=>onAttempt(data.active_attempt!.id)}>Open draft →</button></article>}{data.history.length?<div className="panel table-wrap"><table><thead><tr><th>Exercise</th><th>Mode / level</th><th>Result</th><th>Evidence</th><th>Completed</th></tr></thead><tbody>{data.history.map(h=><tr key={h.id}><td><button className="text-button" onClick={()=>onAttempt(h.id)}>{h.title}</button><div className="fine">Version {h.version}</div></td><td>{h.mode} · L{h.difficulty}</td><td><Badge tone={h.result.outcome==='Correct'?'green':'amber'}>{h.result.outcome} · {h.result.passed}/{h.result.total}</Badge></td><td>{h.result.independent?'Independent':h.hints?'Hints used':h.solution_seen?'Solution seen':'Practice / gap'}</td><td><DateText value={h.at}/></td></tr>)}</tbody></table></div>:<section className="panel"><Empty title="No completed attempts" body="Your saved drafts and submitted evidence survive application restarts. Tests and generated work use a separate temporary profile."/></section>}</>;}

export function Roadmap(){return <><div className="page-heading"><div><div className="eyebrow">SEQUENCED PRODUCT BUILD</div><h1>Labs & take-home projects</h1><p className="muted">The first working release focuses on executed SQL. These later subsystems are planned and have no scored exercises yet.</p></div></div><section className="panel roadmap"><div><Badge tone="green">Available</Badge><h2>SQL training and adaptive evidence</h2><p>12 original exercises, hidden tests, drafts, strict SQL rounds, mastery, mistakes and review scheduling.</p></div>{[['Phase 3','dbt labs','Isolated projects with actual parse/build/test, replay and backfill validation.'],['Phase 4','Reasoning domains','Modeling, metric contracts, incidents and system design with validated model evidence.'],['Phase 5','Mixed interviews','Frozen follow-ups, changing requirements and cross-domain rounds.'],['Phase 6','Take-home simulator','Persistent multi-stage workspaces, datasets, dbt implementation and requirement changes.'],['Phase 7','Curriculum expansion','Grow toward 75–120 reviewed original exercises after runner validation.']].map(([phase,title,body])=><div key={phase}><Badge>{phase} · Planned</Badge><h2>{title}</h2><p>{body}</p></div>)}</section></>;}
