import {useEffect,useRef,useState} from 'react';
import {request} from './api';
import {Badge,Selection} from './components';
import {Editor} from './Editor';
import {useDraft} from './useDraft';
import type {Attempt,Dashboard,Table} from './types';

type RunResult={ok:boolean;columns?:string[];rows?:unknown[][];types?:string[];error?:string;duration_ms:number};
const show=(value:unknown)=>value===null?<span className="null-cell">NULL</span>:String(value);

function Preview({table}:{table:Table}){return <details className="schema-table"><summary><strong>{table.name}</strong><span>{table.rows.length} sample rows</span></summary><div className="table-wrap"><table><thead><tr>{table.columns.map(c=><th key={c.name}>{c.name}<span>{c.type}</span></th>)}</tr></thead><tbody>{table.rows.slice(0,10).map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{show(v)}</td>)}</tr>)}</tbody></table>{!table.rows.length&&<p className="fine">Empty visible table.</p>}</div></details>;}

export function Solve({attempt,data,theme,onUpdate,onContinue,onRevise,onBack,onError}:{attempt:Attempt;data:Dashboard;theme:string;onUpdate:(a:Attempt)=>void;onContinue:()=>void;onRevise:()=>void;onBack:()=>void;onError:(s:string)=>void}) {
 const [busy,setBusy]=useState('');const [output,setOutput]=useState<RunResult|null>(null);const [tab,setTab]=useState('output');
 const [question,setQuestion]=useState('');const [solution,setSolution]=useState<{code:string;explanation:string}|null>(null);
 const [elapsed,setElapsed]=useState(0);const {draft,setDraft,save,state,saveError,sync,recovery,restore,acceptServer}=useDraft(attempt,Boolean(busy));
 const pending=useRef<{request_id:string;code:string;explanation:string;external_assistance:boolean}|null>(null);
 const finished=attempt.status==='completed';const editable=attempt.status==='active'&&!busy;
 useEffect(()=>{try{pending.current=attempt.pending_submission||JSON.parse(localStorage.getItem('ae-submit:'+attempt.id)||'null');}catch{/* saved server request can still be retried */}},[attempt.id]);
 useEffect(()=>{const tick=()=>setElapsed(Math.max(0,Math.floor((Date.now()-new Date(attempt.started_at).getTime())/1000)));tick();const timer=setInterval(tick,1000);return ()=>clearInterval(timer);},[attempt.started_at]);
 const timer= `${Math.floor(elapsed/60)}:${String(elapsed%60).padStart(2,'0')}`;
 function update(a:Attempt){sync(a);onUpdate(a);}
 async function action(label:string,work:()=>Promise<void>){if(busy)return;setBusy(label);try{if(attempt.status==='active')await save();await work();}catch(error){onError((error as Error).message);try{update(await request<Attempt>('/attempts/'+attempt.id));}catch{/* Local copy remains available. */}}finally{setBusy('');}}
 const run=()=>{if(!editable)return;void action('Running SQL…',async()=>{const result=await request<{run:RunResult;attempt:Attempt}>('/attempts/'+attempt.id+'/run','POST',{code:draft.code});setOutput(result.run);setTab('output');update(result.attempt);});};
 const submit=()=>void action('Testing hidden cases…',async()=>{
   const payload={code:draft.code,explanation:draft.explanation,external_assistance:draft.external_assistance};
   let saved=attempt.status==='grading'?attempt.pending_submission:pending.current;
   if(!saved||(attempt.status!=='grading'&&JSON.stringify({code:saved.code,explanation:saved.explanation,external_assistance:saved.external_assistance})!==JSON.stringify(payload)))saved={request_id:crypto.randomUUID(),...payload};
   pending.current=saved;localStorage.setItem('ae-submit:'+attempt.id,JSON.stringify(saved));
   const result=await request<Attempt>('/attempts/'+attempt.id+'/submit','POST',saved);update(result);localStorage.removeItem('ae-submit:'+attempt.id);pending.current=null;setTab('review');
 });
 const hint=()=>void action('Loading hint…',async()=>{const result=await request<{hint?:string;message?:string;denied?:boolean}>('/attempts/'+attempt.id+'/hints','POST');update(await request<Attempt>('/attempts/'+attempt.id));if(result.denied)onError(result.message!);setTab('notes');});
 const clarify=()=>void action('Recording clarification…',async()=>{await request('/attempts/'+attempt.id+'/clarifications','POST',{question});setQuestion('');update(await request<Attempt>('/attempts/'+attempt.id));setTab('notes');});
 const reveal=()=>void action('Opening reference…',async()=>{setSolution(await request('/attempts/'+attempt.id+'/solution','POST'));update(await request<Attempt>('/attempts/'+attempt.id));setTab('solution');});
 return <>
  <button className="text-button back-link" onClick={()=>void action('Saving…',async()=>onBack())}>← Back to overview</button>
  <div className="solve-heading"><div><div className="tag-row"><Badge tone="green">{attempt.mode==='interview'?'Strict SQL interview':attempt.mode==='practice'?'Practice':'Adaptive training'}</Badge><Badge>L{attempt.exercise.difficulty}</Badge><Badge>Version {attempt.exercise.version}</Badge><span className="fine">~{attempt.exercise.estimated_duration} min</span></div><h1>{attempt.exercise.title}</h1></div><div className="attempt-status">{attempt.timed&&!finished&&<span className="timer">◷ {timer}</span>}<span className="fine">{finished?'Attempt complete':`${state} · ${attempt.hint_count} hints`}</span>{attempt.solution_seen&&<Badge tone="amber">Solution seen</Badge>}{attempt.status==='paused'&&<button className="primary" onClick={()=>void action('Resuming…',async()=>update(await request('/attempts/'+attempt.id+'/resume','POST')))}>Resume draft</button>}</div></div>
  {saveError&&<div className="notice amber" role="status">{saveError} Your browser copy is retained. <button onClick={()=>void save().catch(e=>onError(e.message))}>Retry save</button><button onClick={()=>void request<Attempt>('/attempts/'+attempt.id).then(a=>{acceptServer(a);onUpdate(a);}).catch(e=>onError(e.message))}>Load server draft</button></div>}
  {recovery&&<div className="notice amber">A different unsynced draft is saved in this browser. <button onClick={restore}>Restore browser copy</button></div>}
  {attempt.status==='grading'&&<div className="notice amber">Your submission was saved and is being evaluated. If the process was interrupted, retry the saved submission after its short execution lease expires. <button onClick={submit} disabled={Boolean(busy)}>Retry saved submission</button></div>}
  <div className="solve-grid"><section className="problem-panel panel"><div className="eyebrow">THE SCENARIO</div><p className="scenario-context">{attempt.exercise.context}</p><h2>Your task</h2><p className="problem-prompt">{attempt.exercise.prompt}</p><div className="output-contract"><div className="eyebrow">EXPECTED OUTPUT COLUMNS</div><code>{attempt.exercise.expected_columns.map((name,index)=>name+(attempt.exercise.expected_types?.[index]?' : '+attempt.exercise.expected_types[index]:'')).join(' · ')}</code><p className="fine">Unordered rows. Run shows your output on the public fixture; Submit tests the complete contract.</p></div><h2>Source tables</h2>{attempt.exercise.tables.map(t=><Preview key={t.name} table={t}/>)}<div className="problem-bottom"><h3>Ask a clarification</h3><p className="fine">Clarifying the contract counts as a useful interaction, not a hint. Questions and responses are saved.</p><label className="sr-only" htmlFor="clarification">Clarification question</label><textarea id="clarification" value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Confirm a source constraint or metric definition…" disabled={!editable}/><button onClick={clarify} disabled={!editable||!question.trim()}>Ask clarification →</button></div></section>
  <div className="work-area"><section className="editor-panel panel"><div className="editor-heading"><span>⌘ <strong>query.sql</strong></span><span className="fine">DuckDB · isolated execution</span><span className="fine">⌘ / Ctrl + Enter to run</span></div><Editor value={draft.code} onChange={code=>setDraft(d=>({...d,code}))} readOnly={!editable} onRun={run} theme={theme}/><div className="editor-toolbar"><div><button onClick={()=>setDraft(d=>({...d,code:attempt.exercise.starter_code}))} disabled={!editable}>Reset</button><button onClick={()=>void action('Saving draft…',async()=>{})} disabled={!editable}>Save Draft</button><button onClick={hint} disabled={!editable}>{attempt.mode==='interview'?'Hint policy':`Hint ${Math.min(attempt.hint_count+1,3)}/3`}</button></div><div><button className="run-button" onClick={run} disabled={!editable}>▷ Run</button><button className="primary" onClick={submit} disabled={!editable}>{busy||'Submit →'}</button></div></div></section>
   <section className="explanation panel"><label htmlFor="explanation">Assumptions & explanation <span className="fine">Optional · stored, not automatically scored</span></label><textarea id="explanation" value={draft.explanation} onChange={e=>setDraft(d=>({...d,explanation:e.target.value}))} placeholder="State the output grain, assumptions, and how you checked your query…" disabled={!editable}/><label className="check-label"><input type="checkbox" checked={draft.external_assistance} onChange={e=>setDraft(d=>({...d,external_assistance:e.target.checked}))} disabled={!editable||attempt.external_assistance}/>I used external solution assistance (including AI)</label></section>
   <section className="results-panel panel"><div className="tabs" role="tablist">{[['output','Query output'],['review','Submission review'],['notes','Hints & clarifications'],...(solution?[['solution','Reference solution']]:[])].map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} onClick={()=>setTab(id)}>{label}{id==='review'&&finished&&<span className="tab-dot"/>}</button>)}</div><div className="result-body">
    {tab==='output'&&(output?(output.ok?<><div className="output-meta"><Badge tone="green">Query executed</Badge><span>{output.rows?.length} rows · {output.duration_ms} ms</span></div><div className="table-wrap output-table"><table><thead><tr>{output.columns!.map((c,i)=><th key={i}>{c}<span>{output.types?.[i]}</span></th>)}</tr></thead><tbody>{output.rows!.map((row,i)=><tr key={i}>{row.map((v,j)=><td key={j}>{show(v)}</td>)}</tr>)}</tbody></table>{!output.rows?.length&&<p className="fine">The query returned zero rows.</p>}</div></>:<div className="execution-error"><Badge tone="amber">Execution failed</Badge><pre>{output.error}</pre><p>Your query is saved. Revise it and run again.</p></div>):<div className="output-empty"><span>▷</span><h3>Run your first query</h3><p>Inspect your output on the visible fixture before submitting. Hidden expectations remain private.</p></div>)}
    {tab==='review'&&(attempt.result?<><div className="outcome-heading"><div><div className="eyebrow">DETERMINISTIC RESULT</div><h2>{attempt.result.outcome}</h2></div><Badge tone={attempt.result.outcome==='Correct'?'green':'amber'}>{attempt.result.passed} / {attempt.result.total} categories</Badge></div><p className="evidence-label">{attempt.result.evidence_label}</p><div className="review-observation"><strong>Strongest aspect</strong><p>{attempt.result.strongest_aspect}</p><strong>{attempt.result.outcome==='Correct'?'Evidence scope':'Primary issue to investigate'}</strong><p>{attempt.result.primary_issue}</p></div><div className="test-list">{attempt.result.categories.map(c=><details key={c.id}><summary><span className={c.passed?'pass-mark':'fail-mark'}>{c.passed?'✓':'×'}</span><span>{c.category}</span><span className="fine">{c.hidden?'Hidden case':'Visible case'}</span></summary><p>{c.feedback}</p></details>)}</div><details className="review-details"><summary>Senior-level review</summary><p>{attempt.result.senior_review}</p><p className="fine">{attempt.result.reasoning_evaluation}</p></details><details className="review-details" open><summary>Competency updates</summary><div className="mastery-updates">{attempt.result.mastery_updates.map(u=><div key={u.competency_id}><strong>{data.competencies.find(c=>c.id===u.competency_id)?.name||u.competency_id}</strong><span>{u.before} → {u.after}</span></div>)}</div></details><div className="result-actions"><button onClick={onRevise}>Revise this attempt</button><button onClick={reveal}>Show reference solution</button><button className="primary" onClick={onContinue}>Continue Training ↗</button></div><div className="result-recommendation"><Selection value={data.recommendation}/></div></>:<div className="output-empty"><h3>Your review appears after submission</h3><p>Submit runs the hidden fixtures, saves the attempt, and updates competency evidence.</p></div>)}
    {tab==='notes'&&<><div className="interaction-list">{attempt.interactions.filter(i=>['hint','clarification','hint_denied'].includes(i.kind)).map((i,index)=><div key={index}><Badge>{i.kind==='clarification'?'Clarification':i.kind==='hint'?`Hint ${i.level}`:'Hint policy'}</Badge>{i.question&&<p><strong>{i.question}</strong></p>}<p>{i.response||i.message}</p></div>)}{!attempt.interactions.length&&<p className="muted">No assistance or clarification recorded.</p>}</div>{!finished&&<button className="text-button" onClick={reveal} disabled={Boolean(busy)}>Reveal solution and mark this attempt assisted →</button>}</>}
    {tab==='solution'&&solution&&<><Badge tone="amber">Reference · learning material</Badge><pre className="solution-code">{solution.code}</pre><p>{solution.explanation}</p><p className="fine">Reading this is learning, not independent mastery evidence. A different transfer exercise is required.</p></>}
   </div></section>
  </div></div>
 </>;
}
