import { useState } from 'react';
import { api, download } from './api';
import { Badge, Code, Panel } from './components';
import type { Bundle, DataContract, Rule, Scenario } from './types';

function Intro({eyebrow,title,text}: {eyebrow:string;title:string;text:string}) {
  return <div className="page-intro simple"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="intro-copy">{text}</p></div></div>;
}
export function ContractView({scenario}: {scenario:Scenario}) {
  const c = scenario.contract;
  const [sources,setSources] = useState(false);
  return <><Intro eyebrow="DEFINED / THE PRODUCER'S PROMISE" title="Make assumptions explicit." text="A data contract says what must remain true. Tests supply the evidence."/>
    <section className="panel contract-card"><div className="contract-title"><div><p className="eyebrow">DATA CONTRACT · v{c.version}</p><h2 className="mono">{c.dataset_id}</h2></div><span className="contract-stamp">DECLARED<br/>DESIGNED STATE</span></div><div className="contract-grid"><div><span className="eyebrow">GRAIN</span><strong>{c.grain}</strong></div><div><span className="eyebrow">PRIMARY KEY</span><strong className="mono">{c.primary_key.join(' + ')}</strong></div><div><span className="eyebrow">OWNER</span><strong>{c.owner}</strong></div><div><span className="eyebrow">FRESHNESS</span><strong>Arrival age ≤ 2 hours</strong></div></div><p className="semantic-note">{c.semantic_meaning}</p>
      <div className="table-scroll"><table><thead><tr><th>COLUMN</th><th>TYPE</th><th>NULLABILITY</th><th>PRESENCE</th></tr></thead><tbody>{c.columns.map(column=><tr key={column.name}><td className="mono">{column.name}{c.primary_key.includes(column.name)&&<span className="key-mini">KEY</span>}</td><td className="mono">{column.data_type==='DECIMAL'?`DECIMAL(${column.precision},${column.scale})`:column.data_type}</td><td>{column.nullable?'NULLABLE':'NOT NULL'}</td><td>{column.required?'Required':'Optional'}</td></tr>)}</tbody></table></div>
      <div className="relationship-diagram"><span className="mono">fct_orders.customer_id</span><span>must exist →</span><span className="mono">customers.customer_id</span></div><div className="contract-rules">{c.rules.filter(r=>['business_rule','consistency','reconciliation'].includes(r.dimension)).map(rule=><div key={rule.id}><span>↳</span><strong>{rule.name}</strong><p>{rule.description}</p></div>)}</div></section>
    <div className="two-up"><Panel eyebrow="CONTRACT" title="What must remain true"><p>One current row represents one order. Its key is non-null and unique.</p><div className="teaching-quote">“One row per order.”</div></Panel><Panel eyebrow="TEST" title="How we verify it"><p>Count repeated keys and missing identifiers in the actual output.</p><Code value={'COUNT(*) = COUNT(DISTINCT order_id)\nAND order_id IS NOT NULL'}/><p className="muted">The key tests support declared grain. They do not prove the row's business meaning.</p></Panel></div>
    <Panel eyebrow="SAME DOMAIN / DIFFERENT SCENARIO CONTRACTS" title="Six small source concepts"><p>This local fixture is separately versioned. Its net USD totals do not replace Modeling's gross Revenue example.</p><div className="source-chips">{Object.keys(scenario.datasets).filter(k=>k!=='fct_orders').map(k=><span key={k} className="mono">{k} · {scenario.datasets[k].rows?.length} rows</span>)}</div><button className="text-button" onClick={()=>setSources(!sources)}>{sources?'Hide':'Inspect'} source rows ↓</button>{sources&&Object.entries(scenario.datasets).filter(([id])=>id!=='fct_orders').map(([id,ds])=><details key={id}><summary className="mono">{id}</summary><Code value={ds.rows}/></details>)}</Panel>
  </>;
}

export function Builder({scenario,rules,onAdd,onRemove}: {scenario:Scenario;rules:Rule[];onAdd:(rule:Rule)=>void;onRemove:(id:string)=>void}) {
  const [column,setColumn] = useState('order_id');
  const [kind,setKind] = useState('unique');
  const [severity,setSeverity] = useState<Rule['severity']>('CRITICAL');
  const [blocking,setBlocking] = useState(true);
  const [threshold,setThreshold] = useState('100');
  const [values,setValues] = useState('pending,completed,cancelled,shipped');
  const [why,setWhy] = useState('The producer promises this identifier occurs only once; duplicates could inflate counts and revenue.');
  const [error,setError] = useState('');
  const id = `learner_rule_${Math.max(0,...rules.map(r=>Number(r.id.replace('learner_rule_',''))||0))+1}`;
  const dimension = {unique:'uniqueness',not_null:'completeness',accepted_values:'validity',relationship:'referential_integrity'}[kind]!;
  const expectation = kind==='unique'?{kind,columns:[column],null_policy:'fail'}:kind==='not_null'?{kind,column,minimum_rate:String(Number(threshold)/100)}:kind==='accepted_values'?{kind,column,values:values.split(',').map(v=>v.trim()).filter(Boolean),allow_null:false}:{kind,column,parent_dataset:'customers',parent_column:'customer_id',allow_null:false,require_unique_parent:true,maximum_orphan_rate:'0'};
  const compiled:Rule = {id,name:`${column} · ${kind.replaceAll('_',' ')}`,description:why,target:'fct_orders',target_type:'column',dimension,expectation,severity,blocking,owner:scenario.contract.owner,evidence_source:'deterministic_dataset'};
  function add() {
    if (!why.trim() || (kind==='not_null'&&(!Number.isFinite(Number(threshold))||Number(threshold)<0||Number(threshold)>100)) || (kind==='accepted_values'&&!(expectation as {values:string[]}).values.length)) {setError('Provide a purpose, valid completeness threshold and allowed values.');return;}
    onAdd(compiled);
  }
  return <><Intro eyebrow="RULE BUILDER / PURPOSE BEFORE SYNTAX" title="Turn a promise into a check." text="Choose what matters, explain why, and decide whether a breach stops publication."/>
    <div className="two-up"><Panel eyebrow="YOUR EXPECTATION" title="Build a quality rule"><div className="form-grid"><label>Dataset<input value="fct_orders" readOnly/></label><label>Column<select aria-label="Column" value={column} onChange={e=>setColumn(e.target.value)}>{scenario.contract.columns.map(c=><option key={c.name}>{c.name}</option>)}</select></label><label>Expectation<select aria-label="Expectation" value={kind} onChange={e=>setKind(e.target.value)}><option value="unique">Must be unique</option><option value="not_null">Completeness threshold</option><option value="accepted_values">Only accepted values</option><option value="relationship">Customer key must have a parent</option></select></label>{kind==='not_null'&&<label>Minimum non-null percentage<input type="number" min="0" max="100" value={threshold} onChange={e=>setThreshold(e.target.value)}/></label>}{kind==='accepted_values'&&<label>Allowed values, separated by commas<input value={values} onChange={e=>setValues(e.target.value)}/></label>}<label>Severity<select aria-label="Severity" value={severity} onChange={e=>setSeverity(e.target.value as Rule['severity'])}>{['INFO','WARNING','CRITICAL'].map(s=><option key={s}>{s}</option>)}</select></label><label className="checkbox"><input type="checkbox" checked={blocking} onChange={e=>setBlocking(e.target.checked)}/>Block publication on breach or UNKNOWN</label><label>Why does this rule exist?<textarea value={why} onChange={e=>setWhy(e.target.value)} rows={4}/></label></div>{error&&<p role="alert" className="error">{error}</p>}<button className="button primary" onClick={add}>Add rule & return to the lab →</button></Panel>
    <Panel eyebrow="PROVIDER-NEUTRAL OUTPUT" title="Your QualityRule"><Code value={compiled}/><p className="muted">Severity describes impact. Blocking determines the gate. A warning can still block when its blocking policy is enabled.</p></Panel></div>
    <Panel eyebrow="ADDITIONAL RULES" title="The contract stays enforced"><p>Additional rules cannot replace the contract's required checks. They are stored for this browser session and included in evidence exports.</p>{rules.length?rules.map(r=><div className="custom-rule" key={r.id}><strong>{r.name}</strong><span>{r.severity} · {r.blocking?'blocking':'nonblocking'}</span><button className="text-button" onClick={()=>onRemove(r.id)}>Remove</button></div>):<p className="muted">No additional rules yet.</p>}</Panel>
  </>;
}

export function CompatibilityLab({scenario,onError}: {scenario:Scenario;onError:(value:string)=>void}) {
  const [change,setChange]=useState('type');
  const [strict,setStrict]=useState(false);
  const [proof,setProof]=useState(false);
  const [result,setResult]=useState<{status:string;changes:{kind:string;subject:string;classification:string;reason:string}[];limitation:string}|null>(null);
  const [busy,setBusy]=useState(false);
  const before=scenario.contract;
  const after:DataContract=structuredClone(before); after.version='2.0';
  if(change==='type') after.columns.find(c=>c.name==='customer_id')!.data_type='INTEGER';
  if(change==='remove') after.columns=after.columns.filter(c=>c.name!=='ordered_at');
  if(change==='optional') after.columns.push({name:'promo_code',data_type:'STRING',nullable:true,required:false,description:'',precision:18,scale:2});
  if(change==='nullable') after.columns.find(c=>c.name==='shipped_at')!.nullable=false;
  if(change==='grain') after.grain='1 row / order item';
  if(change==='key') after.primary_key=['customer_id'];
  if(change==='meaning') after.semantic_meaning='Gross revenue before returns, rather than net revenue after returns.';
  async function compare(){setBusy(true);onError('');try{setResult(await api('/api/compatibility',{before,after,policy:{allow_optional_additions:!strict},compatible_data:proof?scenario.datasets.fct_orders:null}));}catch(e){onError((e as Error).message);}finally{setBusy(false);}}
  return <><Intro eyebrow="CONTRACT EVOLUTION / COMPATIBILITY LAB" title="Can consumers still rely on it?" text="An additive-looking change can still break a strict consumer. State the policy and inspect the evidence."/>
    <Panel eyebrow="PROPOSED VERSION 2" title="Change the agreement"><div className="compat-controls"><label>Proposed change<select aria-label="Proposed change" value={change} onChange={e=>{setChange(e.target.value);setResult(null);}}><option value="type">customer_id: STRING → INTEGER</option><option value="remove">Remove required ordered_at</option><option value="optional">Add optional promo_code</option><option value="nullable">shipped_at: nullable → NOT NULL</option><option value="grain">Order grain → order-item grain</option><option value="key">Change primary key</option><option value="meaning">Net → gross revenue meaning</option></select></label><label className="checkbox"><input type="checkbox" checked={strict} onChange={e=>{setStrict(e.target.checked);setResult(null);}}/>Consumer forbids optional additions</label><label className="checkbox"><input type="checkbox" checked={proof} onChange={e=>{setProof(e.target.checked);setResult(null);}}/>Supply baseline data as null-tightening evidence</label></div><button className="button primary" onClick={compare} disabled={busy}>{busy?'Comparing…':'Check compatibility'}</button></Panel>
    <div className="two-up"><Panel eyebrow="BEFORE" title="Version 1 · agreed contract"><div className="schema-mini">{before.columns.map(c=><div key={c.name}><span className="mono">{c.name}</span><span>{c.data_type} {c.nullable?'NULLABLE':'NOT NULL'}</span></div>)}</div><p>{before.grain}</p></Panel><Panel eyebrow="AFTER" title="Version 2 · proposed contract"><div className="schema-mini">{after.columns.map(c=><div key={c.name} className={JSON.stringify(c)!==JSON.stringify(before.columns.find(old=>old.name===c.name))?'changed':''}><span className="mono">{c.name}</span><span>{c.data_type} {c.nullable?'NULLABLE':'NOT NULL'}</span></div>)}</div><p>{after.grain}</p></Panel></div>
    {result&&<Panel eyebrow="FACT / STRUCTURAL POLICY ANALYSIS" title={result.status==='COMPATIBLE'?'Compatible under this policy':result.status==='BREAKING'?'Breaking change':'Review required'}>{result.changes.map((c,i)=><div className="compat-change" key={i}><span className={`compat-class ${c.classification.toLowerCase()}`}>{c.classification}</span><div><strong>{c.subject} · {c.kind.replaceAll('_',' ')}</strong><p>{c.reason}</p></div></div>)}<p className="muted">{result.limitation}</p></Panel>}
    <div className="callout">Renaming a column behaves like removal + addition for consumers. Compatible current rows support a rollout; they do not guarantee every future producer or consumer is safe.</div>
  </>;
}

export function TestTypes(){
  const [broken,setBroken]=useState(false);
  return <><Intro eyebrow="TWO QUESTIONS / TWO KINDS OF TEST" title="Logic correctness ≠ data validity." text="A unit test exercises controlled transformation inputs. A data test checks a produced dataset."/>
    <div className="two-up"><Panel eyebrow="UNIT TEST / CONTROLLED EXAMPLE" title="Did the logic return what we expect?"><p>A small illustrative transformation includes completed orders and excludes cancelled ones. It is separate from the quality engine.</p><table><thead><tr><th>status</th><th>amount</th></tr></thead><tbody><tr><td>complete</td><td>100</td></tr><tr><td>cancelled</td><td>200</td></tr></tbody></table><div className="comparison"><div><span className="eyebrow">EXPECTED</span><strong>Revenue = 100</strong></div><span>→</span><div><span className="eyebrow">ACTUAL</span><strong>Revenue = {broken?300:100}</strong></div></div><Badge status={broken?'FAIL':'PASS'}/><label className="checkbox spaced"><input type="checkbox" checked={broken} onChange={e=>setBroken(e.target.checked)}/>Break example logic: include cancelled orders</label><Code value={broken?'SUM(amount)':'SUM(amount WHERE status = complete)'}/></Panel>
    <Panel eyebrow="DATA TEST / OBSERVED OUTPUT" title="Does the table satisfy an assertion?"><p>Inspect actual identifiers from a produced table, regardless of which transformation created it.</p><div className="duplicate-example"><span>1001</span><span>1002</span><span className="duplicate">1002 <small>← duplicate</small></span><span>1003</span></div><div className="comparison"><div><span className="eyebrow">EXPECTED</span><strong>4 rows / 4 IDs</strong></div><span>→</span><div><span className="eyebrow">ACTUAL</span><strong>4 rows / 3 IDs</strong></div></div><Badge status="FAIL"/><p className="muted">The main lab runs data tests against its 10-order fixture. A passing unit test does not certify that today's output is unique.</p></Panel></div>
    <Panel eyebrow="REAL OPTIONAL DBT LAB" title="Both test types have executable evidence"><p>The local dbt/DuckDB check runs native unit tests, model contracts, source tests, built-in generic tests, custom generic rules and a singular business assertion. The core engine runs independently of dbt.</p><Code value={'make check-dbt\n# artifacts: dbt_lab/target/manifest.json\n#            dbt_lab/target/run_results.json'}/><p className="muted">This page's two tiny examples are deterministic illustrations. The dbt command provides separate runtime evidence, saved in docs/test-results.</p></Panel>
  </>;
}

export function Family({scenario,bundle}: {scenario:Scenario;bundle:Bundle|null}) {
  const [dbt,setDbt]=useState<{yaml:string;unsupported:{rule_id:string;reason:string}[];note:string}|null>(null);
  const [error,setError]=useState('');
  async function revealDbt(){try{setDbt(await api('/api/adapters/dbt'));}catch(e){setError((e as Error).message);}}
  return <><Intro eyebrow="CROSS-SYSTEM BOUNDARIES / DESIGNED → OBSERVED" title="One family. Five responsibilities." text="The quality system verifies assumptions. Its consumers decide when to execute, investigate and assess."/>
    <div className="family-flow">{[
      ['MODELING','What should the data look like?','Declares grain, key, schema and business meaning.'],
      ['ORCHESTRATION','When and how does work run?','Builds the fact, calls validation, then obeys the gate.'],
      ['QUALITY','Is the data valid and safe to use?','Runs deterministic rules and returns evidence + publication eligibility.'],
      ['OBSERVABILITY','What happened and what is affected?','Consumes facts to investigate onset, upstream changes and blast radius.'],
      ['TOPTAL','Can the learner diagnose it?','Controls result disclosure, exercises, hints, assessment and scoring.'],
    ].map(([name,question,detail],i)=><div className={`family-card ${i===2?'quality-owner':''}`} key={name}><span className="eyebrow">{String(i+1).padStart(2,'0')} / {name}</span><h2>{question}</h2><p>{detail}</p>{i<4&&<span className="family-arrow">↓</span>}</div>)}</div>
    <div className="two-up"><Panel eyebrow="EXECUTION INTERFACE" title="Build → validate → publish"><Code value={'build_fct_orders\n       ↓\nPOST /api/validate\n       ↓\nquality-gate-v1\n       ↓\nOPEN → eligible to publish\nBLOCKED → withhold publication'}/><p>The caller owns task execution. This lab reports eligibility and simulates withholding a mart; it never schedules or publishes a real model.</p></Panel><Panel eyebrow="EVIDENCE INTERFACE" title="ValidationResult → QualityEvent"><p>QualityEvent carries dataset, rule, status, severity, expected, actual, counts, explicit time, run identity and FACT evidence.</p><button className="button quiet" disabled={!bundle} onClick={()=>download('quality-events.json',bundle?.events)}>Export current QualityEvents ↓</button>{bundle?<Code value={bundle.events.find(e=>e.status==='FAIL')||bundle.events[0]}/>:<div className="empty-note">Run the lab to produce actual events. UNKNOWN is preserved in every mapping.</div>}</Panel></div>
    <Panel eyebrow="PUBLIC INTERFACES / NO SIBLING IMPORTS" title="Use contracts without sharing runtimes"><div className="endpoint-list"><div><strong>Modeling → Quality</strong><code>POST /api/adapters/modeling</code><p>Maps explicit modeling-lab-v1 fact_contract. Observed columns alone are not designed expectations.</p></div><div><strong>Quality → Observability</strong><code>POST /api/adapters/observability</code><p>Maps quality-event-v1 into the existing data-map-v1 TestResult shape. The consumer resolves its own graph IDs.</p></div><div><strong>Toptal → Quality</strong><code>POST /api/scenarios/{scenario.id}/validate</code><p>Returns deterministic evidence. Single-rule requests leave other required gate evidence missing. Toptal owns disclosure and scoring.</p></div></div><p className="muted">Interfaces are implemented locally. Live sibling adapters are future consumer work; this app does not claim those connections are running.</p><a className="text-button" href="/docs" target="_blank" rel="noreferrer">Open API documentation ↗</a></Panel>
    <Panel eyebrow="OPTIONAL PROVIDER / DBT IS AN ADAPTER" title="Translate exact expectations"><p>Supported rules export as current dbt data_tests with explicit arguments and supplied macros. Unmapped expectations remain visible and use the core engine.</p><button className="button quiet" onClick={revealDbt}>Show dbt adapter output ↓</button>{error&&<p role="alert">{error}</p>}{dbt&&<><Code value={dbt.yaml}/><details><summary>{dbt.unsupported.length} rules require core validation or explicit provider binding</summary>{dbt.unsupported.map(item=><p key={item.rule_id}><code>{item.rule_id}</code> — {item.reason}</p>)}</details><p className="muted">{dbt.note}</p></>}<p className="muted">Great Expectations is an optional mapping design at /api/adapters/gx. It is not installed or used to decide gates.</p></Panel>
  </>;
}
